FROM maven:3.9-amazoncorretto-17 AS MAVEN_BUILD
WORKDIR /app
COPY Back-end/. .
RUN mvn clean install  # Use ./mvnw for Maven Wrapper

FROM openjdk:17-slim

COPY --from=MAVEN_BUILD /app/target/demo-0.0.1-SNAPSHOT.jar /app.jar

CMD ["java", "-jar", "/app.jar"]